export enum ErrorCode {
  // Authentication & Authorization
  INVALID_CREDENTIALS = 'AUTH_001',
  TOKEN_EXPIRED = 'AUTH_002',
  TOKEN_INVALID = 'AUTH_003',
  UNAUTHORIZED_ACCESS = 'AUTH_004',
  ACCOUNT_LOCKED = 'AUTH_005',
  ACCOUNT_DISABLED = 'AUTH_006',
  AUTHENTICATION_ERROR = 'AUTH_007',

  // User Management
  USER_NOT_FOUND = 'USER_001',
  USER_ALREADY_EXISTS = 'USER_002',
  USER_INACTIVE = 'USER_003',
  INVALID_USER_DATA = 'USER_004',

  // Phone Verification
  PHONE_ALREADY_VERIFIED = 'PHONE_001',
  PHONE_NOT_VERIFIED = 'PHONE_002',
  INVALID_VERIFICATION_CODE = 'PHONE_003',
  VERIFICATION_CODE_EXPIRED = 'PHONE_004',
  PHONE_ALREADY_IN_USE = 'PHONE_005',
  MAX_ATTEMPTS_EXCEEDED = 'PHONE_006',
  UNSUPPORTED_REGION = 'PHONE_007',
  BLOCKED_REGION = 'PHONE_008',

  // Business Logic
  INVALID_OPERATION = 'BIZ_001',
  OPERATION_NOT_ALLOWED = 'BIZ_002',
  RESOURCE_NOT_FOUND = 'BIZ_003',
  RESOURCE_ALREADY_EXISTS = 'BIZ_004',
  INSUFFICIENT_PERMISSIONS = 'BIZ_005',

  // Validation
  VALIDATION_ERROR = 'VAL_001',
  VALIDATION_FAILED = 'VAL_001',
  REQUIRED_FIELD_MISSING = 'VAL_002',
  INVALID_FORMAT = 'VAL_003',
  VALUE_OUT_OF_RANGE = 'VAL_004',

  // External Services
  EXTERNAL_SERVICE_ERROR = 'EXT_001',
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXT_002',
  EXTERNAL_SERVICE_TIMEOUT = 'EXT_003',
  RATE_LIMIT_EXCEEDED = 'EXT_004',

  // File Operations
  FILE_NOT_FOUND = 'FILE_001',
  FILE_TOO_LARGE = 'FILE_002',
  INVALID_FILE_TYPE = 'FILE_003',
  FILE_UPLOAD_FAILED = 'FILE_004',

  // Database
  DATABASE_ERROR = 'DB_001',
  DUPLICATE_ENTRY = 'DB_002',
  FOREIGN_KEY_VIOLATION = 'DB_003',

  // Generic
  INTERNAL_ERROR = 'INT_001',
  CONFIGURATION_ERROR = 'INT_002',
  UNKNOWN_ERROR = 'UNK_001'
}
